name: Python Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Poetry and install dependencies
        uses: ./.github/actions/setup-env
        with:
          poetry-version: 2.0.0

      - name: Test with pytest
        run: poetry run pytest || echo "PYTEST_FAILED=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: ${{github.actor != 'dependabot[bot]'}}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Fail workflow if pytest failed
        if: env.PYTEST_FAILED == 'true'
        run: exit 1