name: Python Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Poetry and install dependencies
        uses: ./.github/actions/setup-env
        with:
          poetry-version: 2.0.0

      - name: Test with pytest
        run: |
          poetry run pytest -v